<?php
const HEAD = ['HazMon No','Date','Start time','Purpose','From','To','Leg','Mode','Distance (km)',
              'Travel time (min)','Cost (THB)','Reason for choosing','Preferred alternative (and why)'];

function cfg(): array { static $c; return $c ??= require __DIR__ . '/config.php'; }

function db(): PDO {
    $path = cfg()['db_path'];
    if (!is_dir(dirname($path))) mkdir(dirname($path), 0750, true);
    $pdo = new PDO('sqlite:' . $path);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    $pdo->exec('CREATE TABLE IF NOT EXISTS trips (
        id TEXT PRIMARY KEY,            -- generated by the browser; makes retries idempotent
        received_at TEXT NOT NULL,
        hazmon TEXT NOT NULL, date TEXT NOT NULL, time TEXT NOT NULL,
        purpose TEXT NOT NULL, origin TEXT NOT NULL, dest TEXT NOT NULL,
        legs TEXT NOT NULL,             -- JSON array
        sheet_synced INTEGER NOT NULL DEFAULT 0
    )');
    return $pdo;
}

// One row per leg, same layout as the CSV / Google Sheet.
function trip_rows(array $t): array {
    $rows = [];
    foreach ($t['legs'] as $i => $l) {
        $rows[] = [$t['hazmon'], $t['date'], $t['time'], $t['purpose'], $t['origin'], $t['dest'], $i + 1,
                   $l['mode'], $l['km'], $l['min'], $l['cost'], $l['reason'], $l['alt']];
    }
    return $rows;
}
